//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoMilestoneV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int booking_id { get; set; }
        public string pickup_location { get; set; }
        public string dropoff_location { get; set; }
        public string isAccepted { get; set; }
        public Nullable<System.DateTime> from_date { get; set; }
        public Nullable<System.DateTime> to_date { get; set; }
    }
}
