//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoMilestoneV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerBooking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustomerBooking()
        {
            this.CustomerBookingLocations = new HashSet<CustomerBookingLocation>();
        }
    
        public int customer_booking_id { get; set; }
        public string userId { get; set; }
        public int vehicle_id { get; set; }
        public string isAccepted { get; set; }
        public Nullable<System.DateTime> to_date { get; set; }
        public Nullable<System.DateTime> from_date { get; set; }
        public string pickup_location { get; set; }
        public string dropoff_location { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Vehicle Vehicle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerBookingLocation> CustomerBookingLocations { get; set; }
    }
}
