//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoMilestoneV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerBookingLocation
    {
        public int Id { get; set; }
        public int customer_booking_id { get; set; }
        public string longitude { get; set; }
        public string latitude { get; set; }
    
        public virtual CustomerBooking CustomerBooking { get; set; }
    }
}
